Repository SWM-YouQuiz/Authentication-Service, pull requests merged in 2023-07, with the labels that each got.

#5 [YOUQ-79] 프로젝트 초기 설정
  build.gradle.kts
  settings.gradle.kts
  src/main/kotlin/com/youquiz/authentication/AuthenticationApplication.kt
  src/main/kotlin/com/youquiz/authentication/global/config/SecurityConfiguration.kt
  src/main/resources/application.yml
  src/test/kotlin/com/youquiz/authentication/AuthenticationApplicationTest.kt
  src/test/kotlin/com/youquiz/authentication/config/TestConfiguration.kt
  src/test/kotlin/com/youquiz/authentication/util/BaseControllerTest.kt
  src/test/kotlin/com/youquiz/authentication/util/TestUtil.kt
Labels: Chore

#6 [YOUQ-45] 로그인 API 구현
  src/main/kotlin/com/youquiz/authentication/adapter/client/UserClient.kt
  src/main/kotlin/com/youquiz/authentication/domain/User.kt
  src/main/kotlin/com/youquiz/authentication/domain/enum/Role.kt
  src/main/kotlin/com/youquiz/authentication/dto/LoginRequest.kt
  src/main/kotlin/com/youquiz/authentication/dto/LoginResponse.kt
  src/main/kotlin/com/youquiz/authentication/exception/PasswordNotMatchException.kt
  src/main/kotlin/com/youquiz/authentication/exception/UserNotFoundException.kt
  src/main/kotlin/com/youquiz/authentication/global/config/SecurityConfiguration.kt
  src/main/kotlin/com/youquiz/authentication/global/config/WebClientConfiguration.kt
  src/main/kotlin/com/youquiz/authentication/handler/AuthenticationHandler.kt
  src/main/kotlin/com/youquiz/authentication/router/AuthenticationRouter.kt
  src/main/kotlin/com/youquiz/authentication/service/AuthenticationService.kt
  src/test/kotlin/com/youquiz/authentication/controller/AuthenticationControllerTest.kt
  src/test/kotlin/com/youquiz/authentication/fixture/JwtFixture.kt
  src/test/kotlin/com/youquiz/authentication/fixture/UserFixture.kt
  src/test/kotlin/com/youquiz/authentication/service/AuthenticationServiceTest.kt
Labels: Feat

#10 [YOUQ-98] 로그인 API에 리프레쉬 토큰 저장 로직 추가
  src/main/kotlin/com/youquiz/authentication/service/AuthenticationService.kt
  src/test/kotlin/com/youquiz/authentication/service/AuthenticationServiceTest.kt
Labels: Feat, Fix

#12 [YOUQ-103] 백엔드 배포
  src/main/kotlin/com/youquiz/authentication/adapter/client/UserClient.kt
  src/main/kotlin/com/youquiz/authentication/global/config/WebClientConfiguration.kt
  src/main/resources/application.yml
Labels: Chore
