Repository SWM-YouQuiz/Authentication-Service, pull requests merged in 2023-08, with the labels that each got.

#14 [#13] DAO 계층 테스트 외부 의존성 분리
  build.gradle.kts
  src/test/kotlin/com/quizit/authentication/config/RedisTestConfiguration.kt
Labels: Feat, CI / CD

#16 [YOUQ-123] Jenkins CI 연동
  Dockerfile
  Jenkinsfile
Labels: CI / CD

#18 [#17] 모든 API 엔드포인트 prefix 수정
  src/main/kotlin/com/quizit/authentication/global/config/SecurityConfiguration.kt
  src/main/kotlin/com/quizit/authentication/router/AuthenticationRouter.kt
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/kotlin/com/quizit/authentication/controller/AuthenticationControllerTest.kt
  src/test/kotlin/com/quizit/authentication/util/BaseControllerTest.kt
Labels: Feat, Fix

#19 Fix: WebClient Endpoint 수정
  src/main/kotlin/com/quizit/authentication/adapter/client/UserClient.kt
Labels: Fix

#23 [#22] 로그인 API에서의 외부 서비스 통신 수정
  src/main/kotlin/com/quizit/authentication/adapter/client/UserClient.kt
  src/main/kotlin/com/quizit/authentication/dto/request/MatchPasswordRequest.kt
  src/main/kotlin/com/quizit/authentication/dto/response/GetPasswordByUsernameResponse.kt
  src/main/kotlin/com/quizit/authentication/dto/response/MatchPasswordResponse.kt
  src/main/kotlin/com/quizit/authentication/service/AuthenticationService.kt
  src/test/kotlin/com/quizit/authentication/fixture/UserFixture.kt
  src/test/kotlin/com/quizit/authentication/service/AuthenticationServiceTest.kt
Labels: Feat
